// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flux.OnsiteModule.UI.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("FindDonor")]
    public partial class FindDonorFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FindDonor.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FindDonor", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I login the application as a Blood Centers User", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And("I open Active Drive screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I activate a drive", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find Donor Suite")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.TestCaseAttribute("001000101", "ABBOTT", "AARON", "12111935", "M", "7800101", "1", null)]
        [NUnit.Framework.TestCaseAttribute("002000431", "ACOSTA", "ABRAHAM", "10081938", "F", "7800201", "1", null)]
        [NUnit.Framework.TestCaseAttribute("003000761", "ADCOCK", "ADELA", "08051941", "M", "7800301", "1", null)]
        [NUnit.Framework.TestCaseAttribute("004001091", "AGUIRRE", "ADRIANA", "06021944", "M", "7800401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("005001321", "ALBERT", "AILEEN", "03311947", "F", "7800501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("006001651", "ALEXANDER", "ALANA", "01261950", "F", "7800601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("007001981", "ALLISON", "ALBERTO", "11231952", "M", "7800701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("008002211", "ALVARADO", "ALEX", "09211955", "F", "7800801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("009002541", "ANDERSON", "ALEXIS", "07191958", "M", "7800901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("010002871", "ARCHER", "EUGENE", "05161961", "M", "7801001", "1", null)]
        [NUnit.Framework.TestCaseAttribute("011003101", "ARREDONDO", "CHRISTOPHER", "03131964", "F", "7801101", "1", null)]
        [NUnit.Framework.TestCaseAttribute("012003431", "ASHBY", "CHRISTOPHER", "01091967", "F", "7801201", "1", null)]
        [NUnit.Framework.TestCaseAttribute("013003761", "ATKINSON", "EUGENE", "01061969", "M", "7801301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("014004091", "AVILA", "PATRICIA", "12051937", "F", "7801401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("015004321", "BACON", "BENJAMIN", "10021940", "M", "7801501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("016004651", "BAILEY", "REBECCA", "07311943", "M", "7801601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("017004981", "BAKER", "JANET", "05281946", "F", "7801701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("018005211", "BALLARD", "EUGENE", "03251949", "F", "7801801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("019005541", "BARBER", "ANDRES", "01211952", "M", "7801901", "1", null)]
        [NUnit.Framework.TestCaseAttribute("020005871", "BARNARD", "ANGEL", "11181954", "F", "7802001", "1", null)]
        [NUnit.Framework.TestCaseAttribute("021006101", "BARR", "ANGELICA", "09151957", "M", "7802101", "1", null)]
        [NUnit.Framework.TestCaseAttribute("022006431", "BARRON", "ANGIE", "07131960", "M", "7802201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("023006761", "BARTLETT", "ANNA", "05111963", "F", "7802301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("024007091", "BASSETT", "ANNIE", "03081966", "F", "7802401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("025007321", "BAUER", "ANTONIA", "01031969", "M", "7802501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("026007651", "BEACH", "ARCHIE", "02011937", "F", "7802601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("027007981", "BEARD", "ARNOLD", "11301939", "M", "7802701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("028008211", "BEATY", "ARTURO", "09271942", "M", "7802801", "1", null)]
        [NUnit.Framework.TestCaseAttribute("029008541", "BECK", "AUDRA", "07251945", "F", "7802901", "1", null)]
        [NUnit.Framework.TestCaseAttribute("030008871", "BELCHER", "AURORA", "05221948", "F", "7803001", "1", null)]
        [NUnit.Framework.TestCaseAttribute("031009101", "BENDER", "AVA", "03201951", "M", "7803101", "2", null)]
        [NUnit.Framework.TestCaseAttribute("032009431", "BENTLEY", "BART", "01151954", "F", "7803201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("033009761", "BERGER", "BEATRIZ", "11121956", "M", "7803301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("034010091", "BERRY", "BEN", "09101959", "M", "7803401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("035010321", "BINGHAM", "BENJAMIN", "07081962", "F", "7803501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("036010651", "BLACK", "BERNADETTE", "05051965", "F", "7803601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("037010981", "BLACKWELL", "BERT", "03021968", "M", "7803701", "3", null)]
        [NUnit.Framework.TestCaseAttribute("038011211", "BLAND", "BETH", "03311936", "F", "7803801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("039011541", "BLEDSOE", "BETTE", "01271939", "M", "7803901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("040011871", "BOLIN", "BETTYE", "11241941", "M", "7804001", "2", null)]
        [NUnit.Framework.TestCaseAttribute("041012101", "BONNER", "BILLIE", "09211944", "F", "7804101", "2", null)]
        [NUnit.Framework.TestCaseAttribute("042012431", "BOOTH", "BLAINE", "07201947", "F", "7804201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("043012761", "BOWDEN", "BLANCA", "05171950", "M", "7804301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("044013091", "BOWLES", "BOBBIE", "03141953", "F", "7804401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("045013321", "BOX", "BONITA", "01101956", "M", "7804501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("046013651", "BOYLE", "EUGENE", "11071958", "M", "7804601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("047013981", "BRADSHAW", "CHRISTOPHER", "09041961", "F", "7804701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("048014211", "BRANCH", "CHRISTOPHER", "07021964", "F", "7804801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("049014541", "BRANNON", "EUGENE", "04301967", "M", "7804901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("050014871", "BRAUN", "PATRICIA", "02251970", "F", "7805001", "2", null)]
        [NUnit.Framework.TestCaseAttribute("051015101", "BREWER", "BENJAMIM", "03261938", "M", "7805101", "2", null)]
        [NUnit.Framework.TestCaseAttribute("052015431", "BRISCOE", "REBECCA", "01211941", "M", "7805201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("053015761", "BROOKS", "JANET", "11191943", "F", "7805301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("054016091", "BROWNE", "EUGENE", "09161946", "F", "7805401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("055016321", "BRUNER", "CAMERON", "07141949", "M", "7805501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("056016651", "BRYANT", "CANDICE", "05111952", "F", "7805601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("057016981", "BUCKLEY", "CAREN", "03091955", "M", "7805701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("058017211", "BULLOCK", "CARL", "01041958", "M", "7805801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("059017541", "BURGESS", "CARLOS", "11011960", "F", "7805901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("060017871", "BURKETT", "CAROL", "08301963", "F", "7806001", "2", null)]
        [NUnit.Framework.TestCaseAttribute("061018101", "BURNETT", "CAROLINE", "06271966", "M", "7806101", "2", null)]
        [NUnit.Framework.TestCaseAttribute("062018431", "BURROW", "CARROLL", "04241969", "F", "7806201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("063018761", "BUSBY", "CARYN", "05231937", "M", "7806301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("064019091", "BUTLER", "CASSIE", "03201940", "M", "7806401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("065019321", "BYRD", "CATHRYN", "01161943", "F", "7806501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("066019651", "CAIN", "CECIL", "11131945", "F", "7806601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("067019981", "CALLAHAN", "CEDRIC", "09101948", "M", "7806701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("068020211", "CAMACHO", "CESAR", "07091951", "F", "7806801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("069020541", "CAMPBELL", "CHARITY", "05061954", "M", "7806901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("070020871", "CANO", "CHARLES", "03031957", "M", "7807001", "2", null)]
        [NUnit.Framework.TestCaseAttribute("071021101", "CAPPS", "CHERI", "12301959", "F", "7807101", "2", null)]
        [NUnit.Framework.TestCaseAttribute("072021431", "CARLISLE", "CHERYL", "10271962", "F", "7807201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("073021761", "CARMICHAEL", "CHRISTA", "08241965", "M", "7807301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("074022091", "CARPENTER", "CHRISTIE", "06211968", "F", "7807401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("075022321", "CARROLL", "CHRISTOPHER", "07201936", "M", "7807501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("076022651", "CARTWRIGHT", "CINDI", "05181939", "M", "7807601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("077022981", "CASEY", "CLARA", "03151942", "F", "7807701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("078023211", "CASTILLO", "CLARK", "01101945", "F", "7807801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("079023541", "CATES", "CLAUDINE", "11081947", "M", "7807901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("080023871", "CHADWICK", "CLEO", "09051950", "F", "7808001", "2", null)]
        [NUnit.Framework.TestCaseAttribute("081024101", "CHANCE", "CLIFTON", "07031953", "M", "7808101", "2", null)]
        [NUnit.Framework.TestCaseAttribute("082024431", "CHANG", "EUGENE", "04301956", "M", "7808201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("083024761", "CHAPPELL", "CHRISTOPHER", "02261959", "F", "7808301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("084025091", "CHAVEZ", "CHRISTOPHER", "12241961", "F", "7808401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("085025321", "CHEN", "EUGENE", "10211964", "M", "7808501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("086025651", "CHILDRESS", "PATRICIA", "08191967", "F", "7808601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("087025981", "CHRISTENSEN", "BENJAMIN", "06161970", "M", "7808701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("088026211", "CHURCH", "REBECCA", "07151938", "M", "7808801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("089026541", "CLARKE", "JANET", "05121941", "F", "7808901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("090026871", "CLEMENT", "EUGENE", "03091944", "F", "7809001", "2", null)]
        [NUnit.Framework.TestCaseAttribute("091027101", "CLEVELAND", "DALLAS", "01051947", "M", "7809101", "2", null)]
        [NUnit.Framework.TestCaseAttribute("092027431", "CLOUD", "DAN", "11021949", "F", "7809201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("093027761", "COCHRAN", "DANETTE", "08301952", "M", "7809301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("094028091", "COFFMAN", "DANNA", "06281955", "M", "7809401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("095028321", "COLBERT", "DARCY", "04251958", "F", "7809501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("096028651", "COLLIER", "DARLA", "02201961", "F", "7809601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("097028981", "COMPTON", "DARRELL", "12191963", "M", "7809701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("098029211", "CONNELL", "DARRYL", "10161966", "F", "7809801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("099029541", "CONTRERAS", "DAVE", "08131969", "M", "7809901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("100029871", "COOKE", "DAWN", "09111937", "M", "7810001", "2", null)]
        [NUnit.Framework.TestCaseAttribute("101030101", "COPE", "DEANN", "07091940", "F", "7810101", "2", null)]
        [NUnit.Framework.TestCaseAttribute("102030431", "CORNELIUS", "DEBBIE", "05071943", "F", "7810201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("103030761", "COTTEN", "DEBORA", "03041946", "M", "7810301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("104031091", "COURTNEY", "DEE", "12301948", "F", "7810401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("105031321", "COX", "DEIDRE", "10281951", "M", "7810501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("106031651", "CRAIG", "DELIA", "08251954", "M", "7810601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("107031981", "CRAWFORD", "DELORIS", "06221957", "F", "7810701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("108032211", "CROCKER", "DENIS", "04191960", "F", "7810801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("109032541", "CROSBY", "DENNY", "02151963", "M", "7810901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("110032871", "CROW", "DESIREE", "12131965", "F", "7811001", "2", null)]
        [NUnit.Framework.TestCaseAttribute("111033101", "CROWELL", "DEWEY", "10101968", "M", "7811101", "2", null)]
        [NUnit.Framework.TestCaseAttribute("112033431", "CRUZ", "DIANN", "11081936", "M", "7811201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("113033761", "CULVER", "DINA", "09061939", "F", "7811301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("114034091", "CURRY", "DIXIE", "07041942", "F", "7811401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("115034321", "DALTON", "DOMINIC", "05011945", "M", "7811501", "3", null)]
        [NUnit.Framework.TestCaseAttribute("116034651", "DARDEN", "DONALD", "02271948", "F", "7811601", "3", null)]
        [NUnit.Framework.TestCaseAttribute("117034981", "DAVENPORT", "DONNY", "12251950", "M", "7811701", "3", null)]
        [NUnit.Framework.TestCaseAttribute("118035211", "DAVIES", "EUGENE", "10221953", "M", "7811801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("119035541", "DAWSON", "CHRISTOPHER", "08191956", "F", "7811901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("120035871", "DECKER", "CHRISTOPHER", "06171959", "F", "7812001", "3", null)]
        [NUnit.Framework.TestCaseAttribute("127037981", "DODD", "EILEEN", "06281944", "M", "7812701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("128038211", "DOMINGUEZ", "ELDON", "04261947", "F", "7812801", "2", null)]
        [NUnit.Framework.TestCaseAttribute("129038541", "DOOLEY", "ELIAS", "02211950", "M", "7812901", "3", null)]
        [NUnit.Framework.TestCaseAttribute("130038871", "DOTSON", "ELISE", "12191952", "M", "7813001", "3", null)]
        [NUnit.Framework.TestCaseAttribute("131039101", "DOUGLAS", "ELLEN", "10171955", "F", "7813101", "3", null)]
        [NUnit.Framework.TestCaseAttribute("132039431", "DOYLE", "ELMER", "08141958", "F", "7813201", "3", null)]
        [NUnit.Framework.TestCaseAttribute("133039761", "DUCKWORTH", "ELSIE", "06111961", "M", "7813301", "3", null)]
        [NUnit.Framework.TestCaseAttribute("134040091", "DUNCAN", "ELVIRA", "04081964", "F", "7813401", "3", null)]
        [NUnit.Framework.TestCaseAttribute("135040321", "DUNN", "EMILY", "02041967", "M", "7813501", "3", null)]
        [NUnit.Framework.TestCaseAttribute("136040651", "DURHAM", "ENRIQUE", "12021969", "M", "7813601", "3", null)]
        [NUnit.Framework.TestCaseAttribute("137040981", "EASLEY", "ERICK", "12311937", "F", "7813701", "3", null)]
        [NUnit.Framework.TestCaseAttribute("138041211", "ECHOLS", "ERIKA", "10281940", "F", "7813801", "3", null)]
        [NUnit.Framework.TestCaseAttribute("145043321", "ESQUIVEL", "EVAN", "08081960", "M", "7814501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("146043651", "EUBANKS", "EVERETT", "06061963", "F", "7814601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("147043981", "EWING", "FAYE", "04031966", "M", "7814701", "3", null)]
        [NUnit.Framework.TestCaseAttribute("148044311", "FARLEY", "FELIPE", "01291969", "M", "7814801", "3", null)]
        [NUnit.Framework.TestCaseAttribute("149044531", "FARRELL", "FERNANDO", "02271937", "F", "7814901", "3", null)]
        [NUnit.Framework.TestCaseAttribute("150044881", "FERGUSON", "FLORENCE", "12261939", "F", "7815001", "3", null)]
        [NUnit.Framework.TestCaseAttribute("151045101", "FIELD", "FRAN", "10231942", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("152045431", "FINCH", "FRANCIS", "08201945", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("153045761", "FINLEY", "FRANK", "06171948", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("154046191", "FISHER", "EUGENE", "04151951", "M", "7815401", "3", null)]
        [NUnit.Framework.TestCaseAttribute("155046221", "FLANAGAN", "CHRISTOPHER", "02101954", "F", "7815501", "3", null)]
        [NUnit.Framework.TestCaseAttribute("156046451", "FLORES", "CHRISTOPHER", "12081956", "F", "7815601", "3", null)]
        [NUnit.Framework.TestCaseAttribute("163048661", "FRITZ", "GERALDINE", "12201941", "M", "7816301", "3", null)]
        [NUnit.Framework.TestCaseAttribute("164049191", "FRYE", "GERRY", "10171944", "F", "7816401", "3", null)]
        [NUnit.Framework.TestCaseAttribute("165049421", "FULTON", "GILBERTO", "08151947", "M", "7816501", "3", null)]
        [NUnit.Framework.TestCaseAttribute("166049751", "GALLAGHER", "GINNY", "06121950", "M", "7816601", "3", null)]
        [NUnit.Framework.TestCaseAttribute("167049081", "GALVAN", "GLENDA", "04091953", "F", "7816701", "3", null)]
        [NUnit.Framework.TestCaseAttribute("168050221", "GARCIA", "GLORIA", "02051956", "F", "7816801", "3", null)]
        [NUnit.Framework.TestCaseAttribute("169050541", "GARNER", "GRACIE", "12031958", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("170050871", "GARY", "GRAHAM", "09301961", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("171051101", "GATES", "GREGG", "07281964", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("172051531", "GEE", "GRETCHEN", "05261967", "M", "7817201", "3", null)]
        [NUnit.Framework.TestCaseAttribute("173052761", "GIBBONS", "GUILLERMO", "03231970", "F", "7817301", "3", null)]
        [NUnit.Framework.TestCaseAttribute("174052191", "GILBERT", "GWEN", "04211938", "F", "7817401", "3", null)]
        [NUnit.Framework.TestCaseAttribute("181054201", "GOODE", "HERMAN", "01301958", "M", "7818101", "3", null)]
        [NUnit.Framework.TestCaseAttribute("182054331", "GOODSON", "HILDA", "11271960", "F", "7818201", "2", null)]
        [NUnit.Framework.TestCaseAttribute("183054861", "GORMAN", "HOLLY", "09251963", "M", "7818301", "3", null)]
        [NUnit.Framework.TestCaseAttribute("190056971", "GROSS", "EUGENE", "10061948", "M", "7819001", "3", null)]
        [NUnit.Framework.TestCaseAttribute("191057201", "GUERRA", "CHRISTOPHER", "08041951", "F", "7819101", "3", null)]
        [NUnit.Framework.TestCaseAttribute("192057531", "GUNN", "CHRISTOPHER", "06011954", "F", "7819201", "3", null)]
        [NUnit.Framework.TestCaseAttribute("199059641", "HANKS", "JARED", "06131939", "M", "7819901", "3", null)]
        [NUnit.Framework.TestCaseAttribute("200059971", "HANSON", "JAVIER", "04101942", "F", "7820001", "3", null)]
        [NUnit.Framework.TestCaseAttribute("201061101", "HARDING", "JEAN", "02051945", "M", "7820101", "3", null)]
        [NUnit.Framework.TestCaseAttribute("208062211", "HAYES", "JERALD", "11161964", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("209062541", "HEAD", "JERI", "09141967", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("210062871", "HEATH", "JERRY", "07121970", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("217064981", "HEWITT", "JOEL", "07241955", "M", "7821701", "1", null)]
        [NUnit.Framework.TestCaseAttribute("218065211", "HIGGINBOTHAM", "JOHN", "05211958", "F", "7821801", "1", null)]
        [NUnit.Framework.TestCaseAttribute("219065541", "HILL", "JOHNNIE", "03181961", "M", "7821901", "2", null)]
        [NUnit.Framework.TestCaseAttribute("220065871", "HINES", "JON", "01141964", "M", "7822001", "3", null)]
        [NUnit.Framework.TestCaseAttribute("221066101", "HINTON", "JORDAN", "11111966", "F", "7822101", "3", null)]
        [NUnit.Framework.TestCaseAttribute("222066431", "HODGES", "JOSEFINA", "09081969", "F", "7822201", "3", null)]
        [NUnit.Framework.TestCaseAttribute("223066761", "HOGUE", "JOSH", "10071937", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("224067091", "HOLDER", "JOY", "08041940", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("225067321", "HOLLINGSWORTH", "JUANA", "06021943", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("226067651", "HOLMAN", "EUGENE", "03301946", "M", "7822601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("224067981", "HOOD", "CHRISTOPHER", "01251949", "F", "7822701", "2", null)]
        [NUnit.Framework.TestCaseAttribute("228068211", "HOOTEN", "CHRISTOPHER", "11231951", "F", "7822801", "3", null)]
        [NUnit.Framework.TestCaseAttribute("235070321", "HULL", "AIDA", "09031971", "M", "7823501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("236070651", "HUMPHRIES", "BEVERLEY", "10021939", "F", "7823601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("237070981", "HURLEY", "DAWNA", "07301942", "M", "7823701", "3", null)]
        [NUnit.Framework.TestCaseAttribute("238071211", "HUTCHINS", "DORINDA", "05271945", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("239071541", "HUTSON", "ELVIS", "03241948", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("240071871", "INGRAM", "GLYNDA", "01201951", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("241072101", "IRVIN", "LIZA", "11171953", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("242072431", "IVEY", "MERIETTA", "09141956", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("243072761", "JACOB", "NOREEN", "07131959", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("244073091", "JAMES", "OUIDA", "05101962", "M", "7824401", "3", null)]
        [NUnit.Framework.TestCaseAttribute("245073321", "JEFFERSON", "SYED", "03071965", "F", "7824501", "3", null)]
        [NUnit.Framework.TestCaseAttribute("246073651", "JENSEN", "ALONZO", "01031968", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("253075761", "KELLER", "JAYME", "01141953", "M", "7825301", "2", null)]
        [NUnit.Framework.TestCaseAttribute("254076091", "KEMP", "LAQUITA", "11121955", "F", "7825401", "2", null)]
        [NUnit.Framework.TestCaseAttribute("255076321", "KENNEDY", "LEN", "09091958", "M", "7825501", "3", null)]
        [NUnit.Framework.TestCaseAttribute("256076651", "KEY", "MINA", "07071961", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("257076981", "KILGORE", "NED", "05041964", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("258077211", "KING", "RILEY", "03021967", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("259077541", "KIRK", "SONNY", "12281969", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("260077871", "KLEIN", "VENITA", "01261938", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("261078101", "KNIGHT", "LELA", "11231940", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("262078431", "KOCH", "EUGENE", "09211943", "M", "7826201", "3", null)]
        [NUnit.Framework.TestCaseAttribute("263078761", "KRAUSE", "CHRISTOPHER", "07191946", "F", "7826301", "3", null)]
        [NUnit.Framework.TestCaseAttribute("264079091", "KYLE", "CHRISTOPHER", "05161949", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("271081101", "LATHAM", "LLOYD", "02241969", "M", "7827101", "3", null)]
        [NUnit.Framework.TestCaseAttribute("272081431", "LAWRENCE", "LON", "12231971", "F", "7827201", "3", null)]
        [NUnit.Framework.TestCaseAttribute("273081761", "LEAL", "LOREN", "01211940", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("274082091", "LEE", "LORENZO", "11181942", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("275082321", "LESLIE", "LORIE", "09151945", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("276082651", "LEVY", "LORRI", "07131948", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("277082981", "LIN", "LOUIE", "05111951", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("278083211", "LITTLE", "LOURDES", "03081954", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("279083541", "LLOYD", "LUANN", "01031957", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("280083871", "LOGAN", "LUCILLE", "11011959", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("281084101", "LOONEY", "LUIS", "08291962", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("282084431", "LOVE", "LUPE", "06261965", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("289086541", "MAGEE", "MANUEL", "07081950", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("290086871", "MALONE", "MARCI", "05051953", "F", "7829001", "3", null)]
        [NUnit.Framework.TestCaseAttribute("291087101", "MANN", "MARCO", "03021956", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("298089211", "MAYES", "EUGENE", "03141941", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("299089541", "MAYO", "CHRISTOPHER", "01101944", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("300089871", "MCAFEE", "CHRISTOPHER", "11071946", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("307091981", "MCCRACKEN", "MAX", "08181966", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("308092211", "MCDANIEL", "MEGAN", "06151969", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("309092541", "MCDOWELL", "MELBA", "04121972", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("316094651", "MCLEOD", "MIKEL", "04241957", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("317094981", "MCMANUS", "MILTON", "02201960", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("319095211", "MCQUEEN", "MINNIE", "12181962", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("325097556", "MILAM", "MYRNA", "12301947", "M", "7832501", "2", null)]
        [NUnit.Framework.TestCaseAttribute("326097651", "MILLIGAN", "NADINE", "10271950", "F", "7832601", "2", null)]
        [NUnit.Framework.TestCaseAttribute("327098005", "MINOR", "NANCY", "08241953", "M", "7832701", "3", null)]
        [NUnit.Framework.TestCaseAttribute("328098211", "MITCHELL", "NATALIE", "06211956", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("329098541", "MOLINA", "NATHANIEL", "04191959", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("330098871", "MONTGOMERY", "NELDA", "02141962", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("331099101", "MOON", "NELSON", "12121964", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("332099431", "MORALES", "NICHOLAS", "10101967", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("333099761", "MORENO", "NICOLAS", "08071970", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("334104591", "MORRISON", "EUGENE", "09051938", "M", "7833401", "3", null)]
        [NUnit.Framework.TestCaseAttribute("335105561", "MORTON", "CHRISTOPHER", "07031941", "F", "7833501", "3", null)]
        [NUnit.Framework.TestCaseAttribute("336101478", "MOSES", "CHRISTOPHER", "04301944", "F", "7833601", "3", null)]
        [NUnit.Framework.TestCaseAttribute("343102968", "NGUYEN", "PATRICE", "02091964", "M", "7834301", "3", null)]
        [NUnit.Framework.TestCaseAttribute("344103532", "NICHOLSON", "PATSY", "12071966", "F", "7834401", "3", null)]
        [NUnit.Framework.TestCaseAttribute("345103321", "NOBLE", "PATTY", "10041969", "M", "7834501", "3", null)]
        [NUnit.Framework.TestCaseAttribute("346103651", "NORMAN", "PAULETTE", "08011972", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("347103981", "NORTHCUTT", "PEDRO", "08301940", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("348104211", "NOVAK", "PENNY", "06281943", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("349104541", "OBRIEN", "PETER", "04251946", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("350104871", "ODELL", "PHILIP", "02201949", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("351105101", "OGDEN", "POLLY", "12191951", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("352105431", "OLSEN", "RACHAEL", "10161954", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("353105761", "ONEILL", "RAE", "08131957", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("354106091", "ORTIZ", "RAMIRO", "06101960", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("361108101", "PATRICK", "RENE", "06221945", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("362108431", "PAUL", "REYNALDO", "04191948", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("363108761", "PEARCE", "RICHARD", "02151951", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("364109091", "PENA", "RICKIE", "12131953", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("365109321", "PENNINGTON", "ROB", "10101956", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("366109651", "PERKINS", "ROBBY", "08081959", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("367109981", "PETERSEN", "ROBERTO", "06051962", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("368110211", "PETTY", "ROCHELLE", "04021965", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("369110541", "PHILLIPS", "RODERICK", "01291968", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("370110871", "PICKETT", "EUGENE", "11261970", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("371111101", "PIKE", "CHRISTOPHER", "12251938", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("372111431", "PITTS", "CHRISTOPHER", "10221941", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("379113541", "PRESTON", "RUBY", "08021961", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("380113871", "PRITCHETT", "RUFUS", "05301964", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("381114101", "PRUITT", "RUTH", "03281967", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("382114431", "PUGH", "SABRINA", "01231970", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("383114761", "RAGSDALE", "SALVADOR", "11201972", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("384115091", "RAINS", "SAMMIE", "12191940", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("385115321", "RAMSEY", "SANDI", "10171943", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("386115651", "RANEY", "SANTIAGO", "08141946", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("387115981", "RANSOM", "SARAH", "06111949", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("388116211", "RATLIFF", "SCOTT", "04081952", "M", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("389116541", "READ", "SERENA", "02041955", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("390116871", "REECE", "SHANA", "12021957", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("397118981", "RICHTER", "SHEREE", "12141942", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("398119211", "RILEY", "SHERRI", "10111945", "F", "NONE", "4", null)]
        [NUnit.Framework.TestCaseAttribute("399119541", "RITTER", "SHERRY", "08081948", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("406121651", "ROMO", "EUGENE", "05191968", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("407121981", "ROSE", "CHRISTOPHER", "03171971", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("408122211", "ROWE", "CHRISTOPHER", "04151939", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("415124321", "SANDERS", "TAMMI", "01241959", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("416124651", "SANDOVAL", "TAMRA", "11211961", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("417124981", "SARGENT", "TANYA", "09181964", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("424127091", "SHACKELFORD", "THOMAS", "09301949", "M", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("425127321", "SHAH", "TIM", "07281952", "F", "NONE", "5", null)]
        [NUnit.Framework.TestCaseAttribute("426127651", "SHAW", "TINA", "05261955", "F", "NONE", "5", null)]
        public virtual void FindDonorSuite(string ssn, string lastname, string firstname, string dob, string gender, string donorid, string grade, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find Donor Suite", null, @__tags);
#line 12
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 13
 testRunner.Given(string.Format("I have entered {0} {1} {2} {3} and {4}", ssn, lastname, firstname, dob, gender), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.Then(string.Format("a {0} should display at {1}", donorid, grade), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
